// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {proxy} from '../models';
import {profile} from '../models';
import {ai} from '../models';

export function AddProxy(arg1:proxy.Proxy):Promise<void>;

export function Chat(arg1:string,arg2:string):Promise<string>;

export function CheckAllProxies():Promise<Array<proxy.CheckResult>>;

export function CheckProxy(arg1:string):Promise<proxy.CheckResult>;

export function CloseBrowser(arg1:string):Promise<void>;

export function CreateProfile(arg1:string,arg2:profile.CreateOptions):Promise<profile.Profile>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteProxy(arg1:string):Promise<void>;

export function DuplicateProfile(arg1:string):Promise<profile.Profile>;

export function ExportProfile(arg1:string,arg2:string):Promise<void>;

export function GeneratePersonality():Promise<ai.Personality>;

export function GenerateRandomProfile():Promise<profile.Profile>;

export function GetPersonality(arg1:string):Promise<ai.Personality>;

export function GetProfile(arg1:string):Promise<profile.Profile>;

export function GetProfiles():Promise<Array<profile.Profile>>;

export function GetProxies():Promise<Array<proxy.Proxy>>;

export function GetRunningBrowsers():Promise<Array<string>>;

export function GetSchedule(arg1:string):Promise<ai.Schedule>;

export function ImportProfile(arg1:string):Promise<profile.Profile>;

export function ImportProxies(arg1:string,arg2:string):Promise<number>;

export function LaunchBrowser(arg1:string):Promise<void>;

export function UpdatePersonality(arg1:string,arg2:ai.Personality):Promise<void>;

export function UpdateProfile(arg1:profile.Profile):Promise<void>;

export function UpdateSchedule(arg1:string,arg2:ai.Schedule):Promise<void>;
