// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProxy(arg1) {
  return window['go']['app']['App']['AddProxy'](arg1);
}

export function Chat(arg1, arg2) {
  return window['go']['app']['App']['Chat'](arg1, arg2);
}

export function CheckAllProxies() {
  return window['go']['app']['App']['CheckAllProxies']();
}

export function CheckProxy(arg1) {
  return window['go']['app']['App']['CheckProxy'](arg1);
}

export function CloseBrowser(arg1) {
  return window['go']['app']['App']['CloseBrowser'](arg1);
}

export function CreateProfile(arg1, arg2) {
  return window['go']['app']['App']['CreateProfile'](arg1, arg2);
}

export function DeleteProfile(arg1) {
  return window['go']['app']['App']['DeleteProfile'](arg1);
}

export function DeleteProxy(arg1) {
  return window['go']['app']['App']['DeleteProxy'](arg1);
}

export function DuplicateProfile(arg1) {
  return window['go']['app']['App']['DuplicateProfile'](arg1);
}

export function ExportProfile(arg1, arg2) {
  return window['go']['app']['App']['ExportProfile'](arg1, arg2);
}

export function GeneratePersonality() {
  return window['go']['app']['App']['GeneratePersonality']();
}

export function GenerateRandomProfile() {
  return window['go']['app']['App']['GenerateRandomProfile']();
}

export function GetPersonality(arg1) {
  return window['go']['app']['App']['GetPersonality'](arg1);
}

export function GetProfile(arg1) {
  return window['go']['app']['App']['GetProfile'](arg1);
}

export function GetProfiles() {
  return window['go']['app']['App']['GetProfiles']();
}

export function GetProxies() {
  return window['go']['app']['App']['GetProxies']();
}

export function GetRunningBrowsers() {
  return window['go']['app']['App']['GetRunningBrowsers']();
}

export function GetSchedule(arg1) {
  return window['go']['app']['App']['GetSchedule'](arg1);
}

export function ImportProfile(arg1) {
  return window['go']['app']['App']['ImportProfile'](arg1);
}

export function ImportProxies(arg1, arg2) {
  return window['go']['app']['App']['ImportProxies'](arg1, arg2);
}

export function LaunchBrowser(arg1) {
  return window['go']['app']['App']['LaunchBrowser'](arg1);
}

export function UpdatePersonality(arg1, arg2) {
  return window['go']['app']['App']['UpdatePersonality'](arg1, arg2);
}

export function UpdateProfile(arg1) {
  return window['go']['app']['App']['UpdateProfile'](arg1);
}

export function UpdateSchedule(arg1, arg2) {
  return window['go']['app']['App']['UpdateSchedule'](arg1, arg2);
}
